"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import environ
import os


BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Build paths inside the project like this: BASE_DIR / 'subdir'.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-9f!0+gp#q#x3#!v7hg5byv+gj#ww18^i(cw5g=oi(896)0l(1u"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")
# HOST = env("HOST")
# ALLOWED_HOSTS = [HOST, "localhost"]
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=[])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "rest_framework",
    "main",
    "about",
    "chat",
    "crm.apps.CrmConfig",
    "crm_communications.apps.CrmCommunicationsConfig",
    "integrations.apps.IntegrationsConfig",
    "audit.apps.AuditConfig",
    "api.apps.ApiConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": env("ENGINE"),
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "ru-Ru"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "/assets/"
STATIC_FILE_URL = BASE_DIR / "assets"

STATICFILES_DIRS = [
    BASE_DIR / "assets",  # папка с css/js/img рядом с manage.py
]

STATIC_ROOT = env("STATIC_ROOT")
MEDIA_URL = "/media/"
MEDIA_ROOT = env("MEDIA_ROOT")

# DaData API key (stored in .env as DADATA_KEY)
DADATA_KEY = env("DADATA_KEY", default="")

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
TELEGRAM_CHAT_ID = env("TELEGRAM_CHAT_ID", default="")
TELEGRAM_CHAT_CHANNEL = env("TELEGRAM_CHAT_CHANNEL", default="")
TELEGRAM_SUPER_GROUP = env("TELEGRAM_SUPER_GROUP", default="")
BOT_TOKEN = env("BOT_TOKEN", default="")
OPENAI_API_KEY = env("OPENAI_API_KEY", default="")
OPENAI_MODEL = env("OPENAI_MODEL", default="gpt-4o-mini")
OPENAI_ORG = env("OPENAI_ORG", default="")
OPENAI_PROJECT = env("OPENAI_PROJECT", default="")

EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST", default="")
EMAIL_PORT = env("EMAIL_PORT", default=465)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=False)
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=True)
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER or "no-reply@localhost")
SERVER_EMAIL = env("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)
IMAP_HOST = env("IMAP_HOST", default="")
IMAP_PORT = env.int("IMAP_PORT", default=993)
IMAP_USER = env("IMAP_USER", default="")
IMAP_PASSWORD = env("IMAP_PASSWORD", default="")
IMAP_USE_SSL = env.bool("IMAP_USE_SSL", default=True)
IMAP_MAILBOX = env("IMAP_MAILBOX", default="INBOX")
TASK_REMINDER_ESCALATION_MINUTES = env.int("TASK_REMINDER_ESCALATION_MINUTES", default=10)
LEAD_NOTIFICATION_ESCALATION_MINUTES = env.int("LEAD_NOTIFICATION_ESCALATION_MINUTES", default=10)
CRM_PUBLIC_BASE_URL = env("CRM_PUBLIC_BASE_URL", default="")

CHAT_WS_JWT_SECRET = env("CHAT_WS_JWT_SECRET")
CHAT_WS_JWT_TTL_SECONDS = env("CHAT_WS_JWT_TTL_SECONDS")
CHAT_WS_URL = env("CHAT_WS_URL")

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "api.v1.permissions.IsStaffOrReadOnly",
    ],
    "DEFAULT_PAGINATION_CLASS": "api.v1.pagination.StandardResultsSetPagination",
    "PAGE_SIZE": 20,
}
