# Generated by Django 5.2.8 on 2025-12-06 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2503, verbose_name='Действие')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
            },
        ),
        migrations.CreateModel(
            name='Implementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(verbose_name='Номера шага')),
                ('title', models.CharField(max_length=125, verbose_name='Название')),
                ('period', models.CharField(max_length=125, verbose_name='Срок реализации')),
                ('list_actions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionsimplementations', to='main.actions', verbose_name='Список действий')),
            ],
            options={
                'verbose_name': 'Внедрение',
                'verbose_name_plural': 'Внедрения',
            },
        ),
    ]
