# Generated by Django 5.2.8 on 2025-12-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_department_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Improvements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('result', models.CharField(max_length=250, verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Улучшение',
                'verbose_name_plural': 'Улучшения',
            },
        ),
    ]
