# Generated by Django 5.2.8 on 2025-12-06 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_improvements'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='improvements',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='improvementscase', to='main.improvements', verbose_name='Улучшение'),
            preserve_default=False,
        ),
    ]
