# Generated by Django 5.2.8 on 2026-03-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_case_improvements'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(db_index=True, max_length=64, verbose_name='Тип формы')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, default='', max_length=64, verbose_name='Телефон')),
                ('company', models.CharField(blank=True, default='', max_length=255, verbose_name='Компания')),
                ('message', models.TextField(blank=True, default='', verbose_name='Сообщение')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Полезная нагрузка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Отправка формы',
                'verbose_name_plural': 'Отправки форм',
                'ordering': ('-created_at',),
            },
        ),
    ]
