# Generated by Django 5.2.8 on 2026-03-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_formsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='telegram_errors',
            field=models.TextField(blank=True, default='', verbose_name='Ошибки Telegram'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='telegram_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено в Telegram'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='telegram_sent_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Успешных отправок Telegram'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='telegram_total_targets',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего Telegram-чатов'),
        ),
    ]
