# Generated by Django 5.2.8 on 2026-03-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_formsubmission_telegram_errors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='utm_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='UTM-метки'),
        ),
    ]
