# Generated by Django 5.2.8 on 2026-03-14 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128, verbose_name='Действие')),
                ('app_label', models.CharField(max_length=64, verbose_name='Приложение')),
                ('model', models.CharField(max_length=64, verbose_name='Модель')),
                ('object_id', models.CharField(max_length=64, verbose_name='ID объекта')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Записи аудита',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['app_label', 'model'], name='audit_audit_app_lab_c3a7e0_idx'), models.Index(fields=['object_id'], name='audit_audit_object__9f698d_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx')],
            },
        ),
    ]
