# Generated by Django 5.2.8 on 2026-03-14 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Клиент')),
                ('legal_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Юридическое название')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='ИНН')),
                ('website', models.URLField(blank=True, default='', verbose_name='Сайт')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Заметки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DealStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=128, verbose_name='Этап')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_final', models.BooleanField(default=False, verbose_name='Финальный')),
            ],
            options={
                'verbose_name': 'Этап сделки',
                'verbose_name_plural': 'Этапы сделок',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=128, verbose_name='Источник')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Источник лида',
                'verbose_name_plural': 'Источники лидов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=128, verbose_name='Статус')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_final', models.BooleanField(default=False, verbose_name='Финальный')),
            ],
            options={
                'verbose_name': 'Статус лида',
                'verbose_name_plural': 'Статусы лидов',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('first_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Фамилия')),
                ('position', models.CharField(blank=True, default='', max_length=255, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной контакт')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Внешний ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, default='', max_length=64, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('company', models.CharField(blank=True, default='', max_length=255, verbose_name='Компания')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('utm_data', models.JSONField(blank=True, default=dict, verbose_name='UTM')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=16, verbose_name='Приоритет')),
                ('expected_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ожидаемая сумма')),
                ('last_contact_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний контакт')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата конверсии')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_crm_leads', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_leads', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.leadsource', verbose_name='Источник')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.leadstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Сделка')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата закрытия')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('is_won', models.BooleanField(default=False, verbose_name='Успешная')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.client', verbose_name='Клиент')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_deals', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.dealstage', verbose_name='Этап')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.lead', verbose_name='Лид')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('type', models.CharField(choices=[('call', 'Звонок'), ('email', 'Email'), ('meeting', 'Встреча'), ('note', 'Заметка'), ('task', 'Задача')], default='note', max_length=16, verbose_name='Тип')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнено')),
                ('is_done', models.BooleanField(default=False, verbose_name='Завершено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_activities', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.client', verbose_name='Клиент')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.contact', verbose_name='Контакт')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.deal', verbose_name='Сделка')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.lead', verbose_name='Лид')),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активности',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='crm.leadsource', verbose_name='Источник'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['stage'], name='crm_deal_stage_i_e0af80_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['is_won'], name='crm_deal_is_won_c6d284_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['close_date'], name='crm_deal_close_d_712646_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['type'], name='crm_activit_type_e2ae02_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['is_done'], name='crm_activit_is_done_a8c423_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['due_at'], name='crm_activit_due_at_4507ff_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='crm_lead_created_d9bbc3_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='crm_lead_status__0ea863_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source'], name='crm_lead_source__21714c_idx'),
        ),
    ]
