# Generated by Django 5.2.8 on 2026-03-14

from django.db import migrations


LEAD_STATUSES = [
    ("new", "New", 10, False),
    ("in_progress", "In progress", 20, False),
    ("attempting_contact", "Attempting contact", 30, False),
    ("qualified", "Qualified", 40, False),
    ("unqualified", "Unqualified", 50, True),
    ("converted", "Converted", 60, True),
    ("lost", "Lost", 70, True),
    ("spam", "Spam", 80, True),
    ("archived", "Archived", 90, True),
]


def seed_lead_statuses(apps, schema_editor):
    LeadStatus = apps.get_model("crm", "LeadStatus")
    for code, name, order, is_final in LEAD_STATUSES:
        LeadStatus.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "order": order,
                "is_active": True,
                "is_final": is_final,
            },
        )


def reverse_seed_lead_statuses(apps, schema_editor):
    LeadStatus = apps.get_model("crm", "LeadStatus")
    codes = [item[0] for item in LEAD_STATUSES]
    LeadStatus.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_lead_statuses, reverse_seed_lead_statuses),
    ]
