# Generated by Django 5.2.8 on 2026-03-15 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_lead_history_sources_website_session'),
        ('main', '0008_websitesession_websitesessionevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['website_session'], name='crm_lead_website_d29ed5_idx'),
        ),
    ]
