# Generated by Django 5.2.8 on 2026-03-15 10:20

from django.db import migrations, models


def normalize_lead_phone(value: str) -> str:
    digits = "".join(ch for ch in str(value or "") if ch.isdigit())
    if not digits:
        return ""
    if len(digits) == 10:
        digits = f"7{digits}"
    elif len(digits) == 11 and digits.startswith("8"):
        digits = f"7{digits[1:]}"
    return digits[:16]


def populate_phone_normalized(apps, schema_editor):
    Lead = apps.get_model("crm", "Lead")
    for lead in Lead.objects.only("id", "phone").iterator():
        Lead.objects.filter(pk=lead.pk).update(phone_normalized=normalize_lead_phone(lead.phone))


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0011_lead_crm_lead_website_d29ed5_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="phone_normalized",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=16,
                verbose_name="Телефон (нормализованный)",
            ),
        ),
        migrations.RunPython(populate_phone_normalized, migrations.RunPython.noop),
    ]
