# Generated by Django 5.2.8 on 2026-03-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0012_lead_phone_normalized"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Описание сделки"),
        ),
    ]
