# Generated by Django 5.2.8 on 2026-03-16 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0013_deal_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deals",
                to="crm.leadsource",
                verbose_name="Источник сделки",
            ),
        ),
    ]
