# Generated by Django 5.2.8 on 2026-03-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0014_deal_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="deadline_reminder_offset_minutes",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (5, "5 минут"),
                    (10, "10 минут"),
                    (15, "15 минут"),
                    (30, "30 минут"),
                    (60, "1 час"),
                    (120, "2 часа"),
                    (180, "3 часа"),
                ],
                default=30,
                verbose_name="Напомнить за",
            ),
        ),
    ]
