# Generated by Django 5.2.8 on 2026-03-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0015_activity_deadline_reminder_offset_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Описание"),
        ),
    ]
