# Generated by Django 5.2.8 on 2026-03-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0016_lead_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="deadline_reminder_ack_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=32,
                verbose_name="Токен подтверждения напоминания",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="deadline_reminder_acknowledged_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Напоминание подтверждено"),
        ),
        migrations.AddField(
            model_name="activity",
            name="deadline_reminder_email_escalated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Эскалация на email отправлена"),
        ),
    ]
