# Generated by Django 5.2.8 on 2026-03-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_activity_deadline_ack_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('KZT', 'KZT'), ('USD', 'USD'), ('EUR', 'EUR')], default='RUB', max_length=3, verbose_name='Валюта компании'),
        ),
    ]
