# Generated by Django 5.2.8 on 2026-03-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0019_activity_forward_result_to_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="forward_result_to_company",
            new_name="save_company_note",
        ),
        migrations.AlterField(
            model_name="activity",
            name="save_company_note",
            field=models.BooleanField(default=False, verbose_name="Сохранить значимую информацию в компании"),
        ),
        migrations.AddField(
            model_name="activity",
            name="company_note",
            field=models.TextField(blank=True, default="", verbose_name="Факты о компании"),
        ),
    ]
