# Generated by Django 5.2.8 on 2026-03-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0020_activity_company_note_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="work_rules",
            field=models.JSONField(blank=True, default=dict, verbose_name="Правила работы"),
        ),
    ]
