# Generated by Django 5.2.8 on 2026-03-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0021_client_work_rules"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationChannel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("name", models.CharField(max_length=128, unique=True, verbose_name="Канал связи")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
            ],
            options={
                "verbose_name": "Канал связи",
                "verbose_name_plural": "Каналы связи",
                "ordering": ("name",),
            },
        ),
    ]
