# Generated by Django 5.2.8 on 2026-03-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0022_communicationchannel"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="assignment_notification_accepted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Уведомление о новом лиде принято"),
        ),
        migrations.AddField(
            model_name="lead",
            name="assignment_notification_email_escalated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Эскалация уведомления лида на email отправлена"),
        ),
        migrations.AddField(
            model_name="lead",
            name="assignment_notification_sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Уведомление о новом лиде отправлено"),
        ),
        migrations.AddField(
            model_name="lead",
            name="assignment_notification_token",
            field=models.CharField(blank=True, db_index=True, default="", max_length=32, verbose_name="Токен принятия лида"),
        ),
    ]
