# Generated by Django 5.2.8 on 2026-03-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_touch_extra_links'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activity',
            new_name='crm_activit_status_2d8c1f_idx',
            old_name='crm_activit_status_f36e34_idx',
        ),
        migrations.RenameIndex(
            model_name='touch',
            new_name='crm_touch_happene_4afef9_idx',
            old_name='crm_touch_happene_f8ba5a_idx',
        ),
        migrations.RenameIndex(
            model_name='touch',
            new_name='crm_touch_directi_ddcd0e_idx',
            old_name='crm_touch_directi_d9f898_idx',
        ),
        migrations.RenameIndex(
            model_name='touch',
            new_name='crm_touch_lead_id_2332ab_idx',
            old_name='crm_touch_lead_id_37999e_idx',
        ),
        migrations.RenameIndex(
            model_name='touch',
            new_name='crm_touch_deal_id_94d886_idx',
            old_name='crm_touch_deal_id_b18dfd_idx',
        ),
        migrations.RenameIndex(
            model_name='touch',
            new_name='crm_touch_client__58c1d5_idx',
            old_name='crm_touch_client__1d8153_idx',
        ),
        migrations.RenameIndex(
            model_name='touch',
            new_name='crm_touch_contact_fc4f81_idx',
            old_name='crm_touch_contact_e5e3b0_idx',
        ),
        migrations.RenameIndex(
            model_name='touch',
            new_name='crm_touch_task_id_4f1edf_idx',
            old_name='crm_touch_task_id_85d578_idx',
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='touch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='touch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
