# Generated by Django 5.2.8 on 2026-03-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_remove_touch_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='group',
            field=models.CharField(choices=[('internal_task', 'Внутренняя задача'), ('client_task', 'Клиентская задача')], default='internal_task', max_length=32, verbose_name='Группа типа задачи'),
        ),
        migrations.AlterField(
            model_name='touchresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='touchresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
