# Generated by Django 5.2.8 on 2026-03-19 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_tasktype_group_alter_touchresult_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='communication_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.communicationchannel', verbose_name='Канал связи'),
        ),
    ]
