# Generated by Django 5.2.8 on 2026-03-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_activity_communication_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasktype',
            options={'ordering': ('sort_order', 'name'), 'verbose_name': 'Тип задачи', 'verbose_name_plural': 'Типы задач'},
        ),
        migrations.AddField(
            model_name='tasktype',
            name='sort_order',
            field=models.PositiveIntegerField(default=100, verbose_name='Порядок сортировки'),
        ),
    ]
