# Generated by Django 5.2.8 on 2026-03-19 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_tasktype_auto_touch_on_done_tasktype_touch_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='auto_task_on_done',
            field=models.BooleanField(default=False, verbose_name='Автозадача'),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='auto_task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_created_from_types', to='crm.tasktype', verbose_name='Тип автозадачи'),
        ),
    ]
