# Generated by Django 5.2.8 on 2026-03-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_lead_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('todo', 'Новая'), ('in_progress', 'В работе'), ('done', 'Выполнено'), ('canceled', 'Отменено')], default='todo', max_length=16, verbose_name='Статус задачи'),
        ),
    ]
