# Generated by Django 5.2.8 on 2026-03-20 08:12

import crm.models.deal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_rename_crm_dealdoc_deal_id_4564cb_idx_crm_dealdoc_deal_id_423034_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealdocument',
            name='file',
            field=models.FileField(upload_to=crm.models.deal.deal_document_upload_to, verbose_name='Файл'),
        ),
    ]
