# Generated by Django 5.2.8 on 2026-03-20 09:08

import crm.models.deal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_alter_dealdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealdocument',
            name='file',
            field=models.FileField(max_length=500, upload_to=crm.models.deal.deal_document_upload_to, verbose_name='Файл'),
        ),
    ]
