# Generated by Django 5.2.8 on 2026-03-20 10:03

from django.utils.text import slugify
from django.db import migrations, models


def populate_touch_result_codes(apps, schema_editor):
    TouchResult = apps.get_model("crm", "TouchResult")
    used_codes = set(
        TouchResult.objects.exclude(code__isnull=True).exclude(code="").values_list("code", flat=True)
    )
    for item in TouchResult.objects.order_by("id"):
        if item.code:
            continue
        base_code = slugify(item.name, allow_unicode=False).replace("-", "_") or f"touch_result_{item.pk}"
        code = base_code[:64]
        index = 2
        while code in used_codes:
            suffix = f"_{index}"
            code = f"{base_code[: max(1, 64 - len(suffix))]}{suffix}"
            index += 1
        item.code = code
        item.save(update_fields=["code"])
        used_codes.add(code)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0045_alter_dealdocument_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='touchresult',
            options={'ordering': ('sort_order', 'name'), 'verbose_name': 'Результат касания', 'verbose_name_plural': 'Результаты касаний'},
        ),
        migrations.AddField(
            model_name='touchresult',
            name='allowed_touch_types',
            field=models.JSONField(blank=True, default=list, verbose_name='Разрешенные типы касания'),
        ),
        migrations.AddField(
            model_name='touchresult',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='touchresult',
            name='group',
            field=models.CharField(choices=[('no_contact', 'Нет контакта'), ('contact', 'Контакт состоялся'), ('follow_up', 'Следующий шаг'), ('loss', 'Потеря'), ('other', 'Другое')], default='other', max_length=32, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='touchresult',
            name='requires_loss_reason',
            field=models.BooleanField(default=False, verbose_name='Требует причину потери'),
        ),
        migrations.AddField(
            model_name='touchresult',
            name='requires_next_step',
            field=models.BooleanField(default=False, verbose_name='Требует следующий шаг'),
        ),
        migrations.AddField(
            model_name='touchresult',
            name='result_class',
            field=models.CharField(choices=[('positive', 'Позитивный'), ('neutral', 'Нейтральный'), ('negative', 'Негативный')], default='neutral', max_length=16, verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='touchresult',
            name='sort_order',
            field=models.PositiveIntegerField(default=100, verbose_name='Порядок сортировки'),
        ),
        migrations.RunPython(populate_touch_result_codes, migrations.RunPython.noop),
    ]
