# Generated by Django 5.2.8 on 2026-03-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_alter_touchresult_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('event_type', models.CharField(max_length=64, unique=True, verbose_name='Тип события')),
                ('write_timeline', models.BooleanField(default=True, verbose_name='Писать в ленту')),
                ('create_message', models.BooleanField(default=False, verbose_name='Создавать сообщение')),
                ('create_touchpoint_mode', models.CharField(choices=[('none', 'Не создавать'), ('draft', 'Черновик'), ('create', 'Создать')], default='none', max_length=16, verbose_name='Режим создания касания')),
                ('default_outcome_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Код результата по умолчанию')),
                ('require_manager_confirmation', models.BooleanField(default=False, verbose_name='Требовать подтверждение менеджера')),
                ('suggest_next_step_template', models.CharField(blank=True, default='', max_length=128, verbose_name='Шаблон следующего шага')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Правило автоматизации',
                'verbose_name_plural': 'Правила автоматизации',
                'ordering': ('event_type',),
            },
        ),
    ]
