# Generated by Django 5.2.8 on 2026-03-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_automationrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touchresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='touchresult',
            name='updated_at',
        ),
    ]
