# Generated by Django 5.2.8 on 2026-03-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0048_remove_touchresult_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationrule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='automationrule',
            name='updated_at',
        ),
    ]
