# Generated by Django 5.2.8 on 2026-03-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_remove_automationrule_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='default_outcome_code',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Код результата по умолчанию'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='suggest_next_step_template',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Шаблон следующего шага'),
        ),
    ]
