# Generated by Django 5.2.8 on 2026-03-20 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0050_alter_automationrule_default_outcome_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextStepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Шаблон следующего шага',
                'verbose_name_plural': 'Шаблоны следующих шагов',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='automationrule',
            options={'ordering': ('sort_order', 'event_type'), 'verbose_name': 'Правило автоматизации', 'verbose_name_plural': 'Правила автоматизации'},
        ),
        migrations.RemoveField(
            model_name='automationrule',
            name='default_outcome_code',
        ),
        migrations.RemoveField(
            model_name='automationrule',
            name='suggest_next_step_template',
        ),
        migrations.AddField(
            model_name='automationrule',
            name='default_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules', to='crm.touchresult', verbose_name='Результат по умолчанию'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='sort_order',
            field=models.PositiveIntegerField(default=100, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='next_step_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules', to='crm.nextsteptemplate', verbose_name='Шаблон следующего шага'),
        ),
    ]
