# Generated by Django 5.2.8 on 2026-03-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0051_nextsteptemplate_alter_automationrule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutcomeCatalog',
            fields=[
            ],
            options={
                'verbose_name': 'Каталог результата',
                'verbose_name_plural': 'Каталог результатов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crm.touchresult',),
        ),
    ]
