# Generated by Django 5.2.8 on 2026-03-20 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0052_outcomecatalog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutcomeCatalog',
        ),
        migrations.CreateModel(
            name='OutcomeCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Каталог результата',
                'verbose_name_plural': 'Каталог результатов',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='default_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules', to='crm.outcomecatalog', verbose_name='Результат по умолчанию'),
        ),
    ]
