# Generated by Django 5.2.8 on 2026-03-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0053_delete_outcomecatalog_outcomecatalog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touchresult',
            name='group',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='touchresult',
            name='result_class',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Класс'),
        ),
    ]
