# Generated by Django 5.2.8 on 2026-03-20 11:39

import crm.models.client
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0054_alter_touchresult_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='touch',
            name='deal_documents',
            field=models.ManyToManyField(blank=True, related_name='touches', to='crm.dealdocument', verbose_name='Документы сделки'),
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('file', models.FileField(max_length=500, upload_to=crm.models.client.client_document_upload_to, verbose_name='Файл')),
                ('original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Название файла')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.client', verbose_name='Компания')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_client_documents', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Документ компании',
                'verbose_name_plural': 'Документы компаний',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='touch',
            name='client_documents',
            field=models.ManyToManyField(blank=True, related_name='touches', to='crm.clientdocument', verbose_name='Документы компании'),
        ),
    ]
