# Generated by Django 5.2.8 on 2026-03-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0055_touch_deal_documents_clientdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='allow_auto_create_task',
            field=models.BooleanField(default=False, verbose_name='Разрешить автосоздание задачи'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='auto_open_panel',
            field=models.BooleanField(default=False, verbose_name='Автооткрывать панель'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='merge_key',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Ключ цепочки'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='show_in_attention_queue',
            field=models.BooleanField(default=False, verbose_name='Показывать в очереди внимания'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='show_in_summary',
            field=models.BooleanField(default=False, verbose_name='Показывать в summary'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='ui_mode',
            field=models.CharField(choices=[('history_only', 'Только история'), ('signal', 'Сигнал'), ('needs_attention', 'Требует внимания'), ('draft_touch', 'Черновик касания'), ('next_step_prompt', 'Следующий шаг')], default='history_only', max_length=32, verbose_name='UI-режим'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='ui_priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критичный')], default='low', max_length=16, verbose_name='UI-приоритет'),
        ),
    ]
