# Generated by Django 5.2.8 on 2026-03-20 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0056_automationrule_allow_auto_create_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('draft_kind', models.CharField(choices=[('touch', 'Черновик касания'), ('next_step', 'Черновик следующего шага')], default='touch', max_length=16, verbose_name='Тип черновика')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждён'), ('dismissed', 'Отклонён')], default='pending', max_length=16, verbose_name='Статус')),
                ('source_event_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Тип исходного события')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('proposed_direction', models.CharField(blank=True, default='', max_length=16, verbose_name='Предложенное направление')),
                ('proposed_next_step', models.TextField(blank=True, default='', verbose_name='Предложенный следующий шаг')),
                ('proposed_next_step_at', models.DateTimeField(blank=True, null=True, verbose_name='Предложенная дата следующего шага')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда обработан')),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_automation_drafts_acted', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
                ('automation_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='crm.automationrule', verbose_name='Правило автоматизации')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_drafts', to='crm.client', verbose_name='Компания')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_drafts', to='crm.contact', verbose_name='Контакт')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_drafts', to='crm.deal', verbose_name='Сделка')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_drafts', to='crm.lead', verbose_name='Лид')),
                ('next_step_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_drafts', to='crm.nextsteptemplate', verbose_name='Шаблон следующего шага')),
                ('outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_drafts', to='crm.outcomecatalog', verbose_name='Каталог результата')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_automation_drafts', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('proposed_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_drafts', to='crm.communicationchannel', verbose_name='Предложенный канал')),
                ('source_touch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_drafts', to='crm.touch', verbose_name='Исходное касание')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_drafts', to='crm.activity', verbose_name='Задача')),
                ('touch_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_drafts', to='crm.touchresult', verbose_name='Результат касания')),
            ],
            options={
                'verbose_name': 'Черновик автоматизации',
                'verbose_name_plural': 'Черновики автоматизации',
                'ordering': ('status', '-created_at', '-id'),
                'indexes': [models.Index(fields=['status'], name='crm_automat_status_858c3b_idx'), models.Index(fields=['draft_kind'], name='crm_automat_draft_k_759404_idx'), models.Index(fields=['deal'], name='crm_automat_deal_id_87779c_idx'), models.Index(fields=['client'], name='crm_automat_client__d0bc5e_idx'), models.Index(fields=['lead'], name='crm_automat_lead_id_e0e8ff_idx'), models.Index(fields=['source_touch'], name='crm_automat_source__321029_idx')],
            },
        ),
    ]
