# Generated by Django 5.2.8 on 2026-03-20 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0057_automationdraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('item_kind', models.CharField(choices=[('attention', 'Требует внимания'), ('next_step', 'Следующее действие')], default='attention', max_length=16, verbose_name='Тип элемента')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('resolved', 'Обработан'), ('dismissed', 'Отклонён')], default='pending', max_length=16, verbose_name='Статус')),
                ('source_event_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Тип исходного события')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('recommended_action', models.TextField(blank=True, default='', verbose_name='Рекомендованное действие')),
                ('proposed_direction', models.CharField(blank=True, default='', max_length=16, verbose_name='Предложенное направление')),
                ('proposed_next_step', models.TextField(blank=True, default='', verbose_name='Предложенный следующий шаг')),
                ('proposed_next_step_at', models.DateTimeField(blank=True, null=True, verbose_name='Предложенная дата следующего шага')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда обработан')),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_automation_queue_items_acted', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
                ('automation_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='crm.automationrule', verbose_name='Правило автоматизации')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_queue_items', to='crm.client', verbose_name='Компания')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_queue_items', to='crm.contact', verbose_name='Контакт')),
                ('created_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_automation_queue_items', to='crm.activity', verbose_name='Созданная задача')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_queue_items', to='crm.deal', verbose_name='Сделка')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_queue_items', to='crm.lead', verbose_name='Лид')),
                ('next_step_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_queue_items', to='crm.nextsteptemplate', verbose_name='Шаблон следующего шага')),
                ('outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_queue_items', to='crm.outcomecatalog', verbose_name='Каталог результата')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_automation_queue_items', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('proposed_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_queue_items', to='crm.communicationchannel', verbose_name='Предложенный канал')),
                ('source_touch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_queue_items', to='crm.touch', verbose_name='Исходное касание')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_queue_items', to='crm.activity', verbose_name='Связанная задача')),
                ('touch_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_queue_items', to='crm.touchresult', verbose_name='Результат касания')),
            ],
            options={
                'verbose_name': 'Элемент очереди автоматизации',
                'verbose_name_plural': 'Очередь автоматизации',
                'ordering': ('status', '-created_at', '-id'),
                'indexes': [models.Index(fields=['status'], name='crm_automat_status_e842e8_idx'), models.Index(fields=['item_kind'], name='crm_automat_item_ki_3576f7_idx'), models.Index(fields=['deal'], name='crm_automat_deal_id_311c83_idx'), models.Index(fields=['client'], name='crm_automat_client__6ed87f_idx'), models.Index(fields=['lead'], name='crm_automat_lead_id_0f1d99_idx'), models.Index(fields=['source_touch'], name='crm_automat_source__707ca6_idx')],
            },
        ),
    ]
