# Generated by Django 5.2.8 on 2026-03-20 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0058_automationqueueitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationMessageDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждён'), ('dismissed', 'Отклонён')], default='pending', max_length=16, verbose_name='Статус')),
                ('source_event_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Тип исходного события')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок')),
                ('message_subject', models.CharField(blank=True, default='', max_length=255, verbose_name='Тема сообщения')),
                ('message_text', models.TextField(blank=True, default='', verbose_name='Текст сообщения')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда обработан')),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_automation_message_drafts_acted', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
                ('automation_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_drafts', to='crm.automationrule', verbose_name='Правило автоматизации')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_message_drafts', to='crm.client', verbose_name='Компания')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_message_drafts', to='crm.contact', verbose_name='Контакт')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_message_drafts', to='crm.deal', verbose_name='Сделка')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_message_drafts', to='crm.lead', verbose_name='Лид')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_automation_message_drafts', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('proposed_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_message_drafts', to='crm.communicationchannel', verbose_name='Канал сообщения')),
                ('source_touch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_message_drafts', to='crm.touch', verbose_name='Исходное касание')),
            ],
            options={
                'verbose_name': 'Черновик сообщения автоматизации',
                'verbose_name_plural': 'Черновики сообщений автоматизации',
                'ordering': ('status', '-created_at', '-id'),
                'indexes': [models.Index(fields=['status'], name='crm_automat_status_162f29_idx'), models.Index(fields=['deal'], name='crm_automat_deal_id_1ea24c_idx'), models.Index(fields=['client'], name='crm_automat_client__7dd679_idx'), models.Index(fields=['lead'], name='crm_automat_lead_id_2365ba_idx'), models.Index(fields=['source_touch'], name='crm_automat_source__406077_idx')],
            },
        ),
    ]
