# Generated by Django 5.2.8 on 2026-03-20 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0059_automationmessagedraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationOutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('source_event_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Тип исходного события')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок')),
                ('message_subject', models.CharField(blank=True, default='', max_length=255, verbose_name='Тема сообщения')),
                ('message_text', models.TextField(blank=True, default='', verbose_name='Текст сообщения')),
                ('channel_code', models.CharField(blank=True, default='', max_length=32, verbose_name='Код канала')),
                ('provider', models.CharField(blank=True, default='', max_length=32, verbose_name='Провайдер')),
                ('recipient', models.CharField(blank=True, default='', max_length=255, verbose_name='Получатель')),
                ('recipient_display', models.CharField(blank=True, default='', max_length=255, verbose_name='Отображение получателя')),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('manual_required', 'Нужна ручная отправка'), ('failed', 'Ошибка отправки')], default='failed', max_length=32, verbose_name='Статус отправки')),
                ('external_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Внешний ID')),
                ('provider_response', models.JSONField(blank=True, default=dict, verbose_name='Ответ провайдера')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда подтверждено')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда отправлено')),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_automation_outbound_messages_acted', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил отправку')),
                ('automation_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='crm.automationrule', verbose_name='Правило автоматизации')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_outbound_messages', to='crm.client', verbose_name='Компания')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_outbound_messages', to='crm.contact', verbose_name='Контакт')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_outbound_messages', to='crm.deal', verbose_name='Сделка')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_outbound_messages', to='crm.lead', verbose_name='Лид')),
                ('message_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='crm.automationmessagedraft', verbose_name='Черновик сообщения')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_automation_outbound_messages', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('source_touch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_outbound_messages', to='crm.touch', verbose_name='Исходное касание')),
            ],
            options={
                'verbose_name': 'Исходящее сообщение автоматизации',
                'verbose_name_plural': 'Исходящие сообщения автоматизации',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['status'], name='crm_automat_status_83a9cc_idx'), models.Index(fields=['channel_code'], name='crm_automat_channel_382e8f_idx'), models.Index(fields=['deal'], name='crm_automat_deal_id_2bf26c_idx'), models.Index(fields=['client'], name='crm_automat_client__6bd35f_idx'), models.Index(fields=['lead'], name='crm_automat_lead_id_bd056b_idx'), models.Index(fields=['message_draft'], name='crm_automat_message_8d72f1_idx'), models.Index(fields=['source_touch'], name='crm_automat_source__cdc30d_idx')],
            },
        ),
    ]
