# Generated by Django 5.2.8 on 2026-03-22 17:44

import crm.models.lead
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0060_automationoutboundmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('file', models.FileField(max_length=500, upload_to=crm.models.lead.lead_document_upload_to, verbose_name='Файл')),
                ('original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Название файла')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.lead', verbose_name='Лид')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_lead_documents', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Документ лида',
                'verbose_name_plural': 'Документы лидов',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['lead'], name='crm_leaddoc_lead_id_30aa7e_idx')],
            },
        ),
    ]
