# Generated by Django 5.2.8 on 2026-03-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0062_taskcategory_userrole_tasktype_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-created_at',), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
