# Generated by Django 5.2.8 on 2026-03-23 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0063_alter_activity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userroleassignment',
            options={'ordering': ('user__username', 'role__sort_order', 'role__name'), 'verbose_name': 'Назначение роли пользователю', 'verbose_name_plural': 'Назначения ролей пользователям'},
        ),
    ]
