# Generated by Django 5.2.8 on 2026-03-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0064_alter_userroleassignment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='group',
            field=models.CharField(choices=[('internal_task', 'Внутренняя задача'), ('client_task', 'Клиентская задача')], default='internal_task', max_length=32, verbose_name='Группа задач'),
        ),
    ]
