# Generated by Django 5.2.8 on 2026-03-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0065_alter_tasktype_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcategory',
            name='requires_follow_up_task_on_done',
            field=models.BooleanField(default=False, verbose_name='Требует следующую задачу при завершении'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='satisfies_deal_next_step_requirement',
            field=models.BooleanField(default=False, verbose_name='Закрывает требование следующего шага по сделке'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='uses_communication_channel',
            field=models.BooleanField(default=False, verbose_name='Использует канал связи'),
        ),
    ]
