# Generated by Django 5.2.8 on 2026-03-30 08:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0076_alter_settlementdocument_document_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='settlementallocation',
            new_name='crm_settlem_source__3a15a4_idx',
            old_name='crm_settlem_source__14f60d_idx',
        ),
        migrations.RenameIndex(
            model_name='settlementallocation',
            new_name='crm_settlem_target__2cfd8d_idx',
            old_name='crm_settlem_target__00f639_idx',
        ),
        migrations.RenameIndex(
            model_name='settlementcontract',
            new_name='crm_settlem_client__b080b1_idx',
            old_name='crm_settlem_client__bdf24c_idx',
        ),
        migrations.RenameIndex(
            model_name='settlementdocument',
            new_name='crm_settlem_client__bf04a1_idx',
            old_name='crm_settlem_client__57d59c_idx',
        ),
        migrations.RenameIndex(
            model_name='settlementdocument',
            new_name='crm_settlem_client__3515cf_idx',
            old_name='crm_settlem_client__237403_idx',
        ),
        migrations.RenameIndex(
            model_name='settlementdocument',
            new_name='crm_settlem_due_dat_a37ed2_idx',
            old_name='crm_settlem_due_dat_5c0d70_idx',
        ),
        migrations.AlterField(
            model_name='settlementallocation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Сумма распределения'),
        ),
        migrations.AlterField(
            model_name='settlementdocument',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='settlementdocument',
            name='open_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Остаток'),
        ),
    ]
