# Generated by Django 5.2.8 on 2026-03-30 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0077_rename_crm_settlem_source__14f60d_idx_crm_settlem_source__3a15a4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementDocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('document_type', models.CharField(max_length=32, unique=True, verbose_name='Тип документа')),
                ('next_number', models.PositiveIntegerField(default=1235, verbose_name='Следующий номер')),
            ],
            options={
                'verbose_name': 'Счетчик документов взаиморасчетов',
                'verbose_name_plural': 'Счетчики документов взаиморасчетов',
                'ordering': ('document_type',),
            },
        ),
        migrations.AddField(
            model_name='settlementdocument',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_documents', to='crm.deal', verbose_name='Сделка'),
        ),
    ]
