# Generated by Django 5.2.8 on 2026-03-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0078_settlementdocumentsequence_settlementdocument_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlementdocument',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Счет'), ('realization', 'Акт / накладная'), ('supplier_receipt', 'Поступление от поставщика'), ('incoming_payment', 'Оплата входящая'), ('outgoing_payment', 'Оплата исходящая'), ('debt_adjustment', 'Корректировка долга'), ('refund', 'Возврат')], max_length=32, verbose_name='Тип документа'),
        ),
    ]
