# Generated by Django 5.2.8 on 2026-03-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0079_alter_settlementdocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_type',
            field=models.CharField(choices=[('own', 'Собственные организации'), ('client', 'Клиент'), ('supplier', 'Поставщик')], default='client', max_length=16, verbose_name='Тип компании'),
        ),
    ]
