# Generated by Django 5.2.8 on 2026-03-31 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0080_client_company_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealdocument",
            name="settlement_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deal_documents",
                to="crm.settlementdocument",
                verbose_name="Документ взаиморасчетов",
            ),
        ),
        migrations.AddField(
            model_name="settlementdocument",
            name="generator_payload",
            field=models.JSONField(blank=True, default=dict, verbose_name="Параметры генерации"),
        ),
        migrations.AddIndex(
            model_name="dealdocument",
            index=models.Index(fields=["settlement_document"], name="crm_dealdoc_settlem_3df263_idx"),
        ),
    ]
