# Generated by Django 5.2.8 on 2026-03-31 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0081_dealdocument_settlement_document_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dealdocument',
            new_name='crm_dealdoc_settlem_594f15_idx',
            old_name='crm_dealdoc_settlem_3df263_idx',
        ),
    ]
