# Generated by Django 5.2.8 on 2026-03-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0082_rename_crm_dealdoc_settlem_3df263_idx_crm_dealdoc_settlem_594f15_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementcontract',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Стоимость в час'),
        ),
    ]
