# Generated by Django 5.2.8 on 2026-03-31 09:08

import crm.models.settlement
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0083_settlementcontract_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementcontract',
            name='advance_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Размер аванса, %'),
        ),
        migrations.AddField(
            model_name='settlementcontract',
            name='claim_response_days',
            field=models.PositiveIntegerField(default=5, verbose_name='Срок ответа на претензию, дней'),
        ),
        migrations.AddField(
            model_name='settlementcontract',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=crm.models.settlement.settlement_contract_upload_to, verbose_name='Файл договора'),
        ),
        migrations.AddField(
            model_name='settlementcontract',
            name='generator_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Параметры генерации'),
        ),
        migrations.AddField(
            model_name='settlementcontract',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название файла'),
        ),
        migrations.AddField(
            model_name='settlementcontract',
            name='termination_notice_days',
            field=models.PositiveIntegerField(default=5, verbose_name='Срок уведомления о расторжении, дней'),
        ),
        migrations.AddField(
            model_name='settlementcontract',
            name='warranty_days',
            field=models.PositiveIntegerField(default=31, verbose_name='Гарантийный срок, дней'),
        ),
    ]
