# Generated by Django 5.2.8 on 2026-04-01 10:08

import django.db.models.deletion
from django.db import migrations, models
from django.core.management.color import no_style


def copy_lead_sources_to_traffic_sources(apps, schema_editor):
    LeadSource = apps.get_model("crm", "LeadSource")
    TrafficSource = apps.get_model("crm", "TrafficSource")

    for source in LeadSource.objects.all().iterator():
        TrafficSource.objects.update_or_create(
            id=source.id,
            defaults={
                "name": source.name,
                "code": source.code,
                "description": source.description,
                "is_active": source.is_active,
            },
        )

    sequence_sql = schema_editor.connection.ops.sequence_reset_sql(no_style(), [TrafficSource])
    for statement in sequence_sql:
        schema_editor.execute(statement)


def reverse_copy_lead_sources_to_traffic_sources(apps, schema_editor):
    TrafficSource = apps.get_model("crm", "TrafficSource")
    TrafficSource.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0084_settlementcontract_advance_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=128, verbose_name='Источник')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Источник трафика',
                'verbose_name_plural': 'Источники трафика',
                'ordering': ('name',),
            },
        ),
        migrations.RunPython(copy_lead_sources_to_traffic_sources, reverse_copy_lead_sources_to_traffic_sources),
        migrations.AlterModelOptions(
            name='leadsource',
            options={'ordering': ('name',), 'verbose_name': 'Действие на сайте', 'verbose_name_plural': 'Действия на сайте'},
        ),
        migrations.AlterField(
            model_name='lead',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='tracked_leads', to='crm.leadsource', verbose_name='Действия на сайте'),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='client',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='crm.trafficsource', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.trafficsource', verbose_name='Источник сделки'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.trafficsource', verbose_name='Источник'),
        ),
    ]
