# Generated by Django 5.2.8 on 2026-03-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64, verbose_name='Источник')),
                ('event_type', models.CharField(max_length=128, verbose_name='Тип события')),
                ('external_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Внешний ID')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('process_error', models.TextField(blank=True, default='', verbose_name='Ошибка обработки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано в')),
            ],
            options={
                'verbose_name': 'Webhook событие',
                'verbose_name_plural': 'Webhook события',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['source'], name='integration_source_e75ab8_idx'), models.Index(fields=['event_type'], name='integration_event_t_ce84f1_idx'), models.Index(fields=['is_processed'], name='integration_is_proc_a59b63_idx')],
            },
        ),
    ]
