# Generated by Django 5.2.8 on 2026-03-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_userintegrationprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userintegrationprofile",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254, verbose_name="Email для уведомлений"),
        ),
    ]
