# Generated by Django 5.2.8 on 2026-03-27 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0070_alter_automationrule_create_message'),
        ('integrations', '0003_userintegrationprofile_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelephonyEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('novofon', 'Novofon')], max_length=32, verbose_name='Провайдер')),
                ('event_type', models.CharField(blank=True, default='', max_length=128, verbose_name='Тип события')),
                ('external_event_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Внешний ID события')),
                ('external_call_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Внешний ID звонка')),
                ('deduplication_key', models.CharField(blank=True, default='', max_length=255, verbose_name='Ключ дедупликации')),
                ('payload_json', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('headers_json', models.JSONField(blank=True, default=dict, verbose_name='Headers')),
                ('status', models.CharField(choices=[('received', 'Получено'), ('queued', 'В очереди'), ('processed', 'Обработано'), ('failed', 'Ошибка'), ('ignored_duplicate', 'Дубликат')], default='received', max_length=32, verbose_name='Статус')),
                ('error_text', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Количество попыток')),
            ],
            options={
                'verbose_name': 'Событие телефонии',
                'verbose_name_plural': 'События телефонии',
                'ordering': ('-received_at', '-id'),
                'indexes': [models.Index(fields=['provider', 'status'], name='integration_provide_b054cc_idx'), models.Index(fields=['provider', 'external_call_id'], name='integration_provide_de85c0_idx'), models.Index(fields=['deduplication_key'], name='integration_dedupli_7bb8ec_idx'), models.Index(fields=['external_event_id'], name='integration_externa_e289c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelephonyProviderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider', models.CharField(choices=[('novofon', 'Novofon')], max_length=32, unique=True, verbose_name='Провайдер')),
                ('enabled', models.BooleanField(default=False, verbose_name='Интеграция включена')),
                ('api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='API key')),
                ('api_secret', models.CharField(blank=True, default='', max_length=255, verbose_name='API secret')),
                ('api_base_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Базовый URL API')),
                ('webhook_path', models.CharField(blank=True, default='/api/integrations/novofon/webhook/', max_length=255, verbose_name='Путь webhook')),
                ('create_lead_for_unknown_number', models.BooleanField(default=False, verbose_name='Создавать лид для неизвестного номера')),
                ('create_task_for_missed_call', models.BooleanField(default=False, verbose_name='Создавать задачу по пропущенному звонку')),
                ('link_calls_to_open_deal_only', models.BooleanField(default=True, verbose_name='Привязывать звонки только к открытой сделке')),
                ('allowed_virtual_numbers', models.JSONField(blank=True, default=list, verbose_name='Разрешенные виртуальные номера')),
                ('is_debug_logging_enabled', models.BooleanField(default=False, verbose_name='Расширенное логирование')),
                ('webhook_shared_secret', models.CharField(blank=True, default='', max_length=255, verbose_name='Секрет webhook')),
                ('settings_json', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные настройки')),
                ('last_connection_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка подключения')),
                ('last_connection_status', models.CharField(blank=True, default='', max_length=32, verbose_name='Статус последней проверки')),
                ('last_connection_error', models.TextField(blank=True, default='', verbose_name='Ошибка последней проверки')),
                ('default_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_telephony_provider_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный по умолчанию')),
            ],
            options={
                'verbose_name': 'Аккаунт телефонии',
                'verbose_name_plural': 'Аккаунты телефонии',
                'ordering': ('provider',),
            },
        ),
        migrations.CreateModel(
            name='PhoneCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider', models.CharField(choices=[('novofon', 'Novofon')], max_length=32, verbose_name='Провайдер')),
                ('external_call_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Внешний ID звонка')),
                ('external_parent_event_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Внешний ID события')),
                ('direction', models.CharField(choices=[('inbound', 'Входящий'), ('outbound', 'Исходящий')], default='inbound', max_length=16, verbose_name='Направление')),
                ('status', models.CharField(choices=[('ringing', 'Звонит'), ('answered', 'Отвечен'), ('missed', 'Пропущен'), ('completed', 'Завершен'), ('failed', 'Ошибка'), ('canceled', 'Отменен')], default='ringing', max_length=16, verbose_name='Статус')),
                ('phone_from', models.CharField(blank=True, default='', max_length=64, verbose_name='Номер from')),
                ('phone_to', models.CharField(blank=True, default='', max_length=64, verbose_name='Номер to')),
                ('client_phone_normalized', models.CharField(blank=True, default='', max_length=16, verbose_name='Номер клиента (нормализованный)')),
                ('virtual_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Виртуальный номер')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Ответ')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность')),
                ('talk_duration_sec', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность разговора')),
                ('recording_url', models.CharField(blank=True, default='', max_length=500, verbose_name='URL записи')),
                ('raw_payload_last', models.JSONField(blank=True, default=dict, verbose_name='Последний payload')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_calls', to='crm.client', verbose_name='Компания')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_calls', to='crm.contact', verbose_name='Контакт')),
                ('crm_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_calls', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь CRM')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_calls', to='crm.deal', verbose_name='Сделка')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_calls', to='crm.lead', verbose_name='Лид')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_phone_calls', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Телефонный звонок',
                'verbose_name_plural': 'Телефонные звонки',
                'ordering': ('-started_at', '-created_at', '-id'),
                'indexes': [models.Index(fields=['external_call_id'], name='integration_externa_23b94e_idx'), models.Index(fields=['client_phone_normalized'], name='integration_client__b0bff5_idx'), models.Index(fields=['started_at'], name='integration_started_736b6b_idx'), models.Index(fields=['crm_user'], name='integration_crm_use_6e455b_idx'), models.Index(fields=['deal'], name='integration_deal_id_2bd88b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_call_id', ''), _negated=True), fields=('provider', 'external_call_id'), name='integrations_unique_provider_external_call_id')],
            },
        ),
        migrations.CreateModel(
            name='TelephonyUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('novofon_employee_id', models.CharField(max_length=128, verbose_name='ID сотрудника Novofon')),
                ('novofon_extension', models.CharField(blank=True, default='', max_length=64, verbose_name='Внутренний номер')),
                ('novofon_full_name', models.CharField(blank=True, default='', max_length=255, verbose_name='ФИО в Novofon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_default_owner', models.BooleanField(default=False, verbose_name='Ответственный по умолчанию')),
                ('external_payload', models.JSONField(blank=True, default=dict, verbose_name='Данные сотрудника')),
                ('crm_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telephony_user_mappings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь CRM')),
                ('provider_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mappings', to='integrations.telephonyprovideraccount', verbose_name='Аккаунт провайдера')),
            ],
            options={
                'verbose_name': 'Сопоставление пользователя телефонии',
                'verbose_name_plural': 'Сопоставления пользователей телефонии',
                'ordering': ('novofon_full_name', 'novofon_extension', 'id'),
                'indexes': [models.Index(fields=['novofon_extension'], name='integration_novofon_892217_idx'), models.Index(fields=['is_active'], name='integration_is_acti_f5c3f5_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider_account', 'novofon_employee_id'), name='integrations_unique_provider_employee_mapping'), models.UniqueConstraint(condition=models.Q(('crm_user__isnull', False)), fields=('provider_account', 'crm_user'), name='integrations_unique_provider_crm_user_mapping')],
            },
        ),
    ]
