# Generated by Django 5.2.8 on 2026-03-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_telephonyeventlog_telephonyprovideraccount_phonecall_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telephonyeventlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Получено"),
                    ("queued", "В очереди"),
                    ("processing", "Обрабатывается"),
                    ("processed", "Обработано"),
                    ("failed", "Ошибка"),
                    ("ignored_duplicate", "Дубликат"),
                ],
                default="received",
                max_length=32,
                verbose_name="Статус",
            ),
        ),
    ]
