# Generated by Django 5.2.8 on 2026-04-01 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0085_trafficsource_alter_leadsource_options_and_more'),
        ('integrations', '0005_alter_telephonyeventlog_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecall',
            name='transcription_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Транскрибация завершена'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='transcription_error',
            field=models.TextField(blank=True, default='', verbose_name='Ошибка транскрибации'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='transcription_external_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Внешний ID транскрибации'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='transcription_recording_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='URL записи для транскрибации'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='transcription_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Транскрибация запрошена'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='transcription_status',
            field=models.CharField(choices=[('not_requested', 'Не запрошена'), ('queued', 'В очереди'), ('processing', 'Обрабатывается'), ('completed', 'Готово'), ('failed', 'Ошибка')], default='not_requested', max_length=32, verbose_name='Статус транскрибации'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='transcription_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст транскрибации'),
        ),
        migrations.AddIndex(
            model_name='phonecall',
            index=models.Index(fields=['transcription_external_id'], name='integration_transcr_67e7a2_idx'),
        ),
        migrations.AddIndex(
            model_name='phonecall',
            index=models.Index(fields=['transcription_status'], name='integration_transcr_110d8d_idx'),
        ),
    ]
