# Generated by Django 5.2.8 on 2026-04-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0085_trafficsource_alter_leadsource_options_and_more"),
        ("integrations", "0006_phonecall_transcription_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonecall",
            name="touch",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="phone_call",
                to="crm.touch",
                verbose_name="Касание",
            ),
        ),
    ]
