# Generated by Django 5.2.8 on 2026-04-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0007_phonecall_touch"),
    ]

    operations = [
        migrations.CreateModel(
            name="LlmProviderAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True, verbose_name="Название")),
                ("provider", models.CharField(choices=[("openai", "OpenAI"), ("deepseek", "DeepSeek"), ("yandexgpt", "YandexGPT"), ("custom", "Свой провайдер")], default="custom", max_length=32, verbose_name="Провайдер")),
                ("api_style", models.CharField(choices=[("openai_compatible", "OpenAI-совместимый API")], default="openai_compatible", max_length=32, verbose_name="Стиль API")),
                ("base_url", models.CharField(blank=True, default="", max_length=500, verbose_name="Базовый URL API")),
                ("model", models.CharField(blank=True, default="", max_length=255, verbose_name="Модель")),
                ("api_key_encrypted", models.TextField(blank=True, default="", verbose_name="API key (зашифрованный)")),
                ("api_key_last4", models.CharField(blank=True, default="", max_length=16, verbose_name="Последние символы API key")),
                ("organization", models.CharField(blank=True, default="", max_length=255, verbose_name="Organization")),
                ("project", models.CharField(blank=True, default="", max_length=255, verbose_name="Project")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("use_for_touch_analysis", models.BooleanField(default=False, verbose_name="Использовать для анализа касаний")),
                ("priority", models.PositiveIntegerField(default=100, verbose_name="Приоритет")),
            ],
            options={
                "verbose_name": "LLM провайдер",
                "verbose_name_plural": "LLM провайдеры",
                "ordering": ("priority", "name", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="llmprovideraccount",
            index=models.Index(fields=["is_active", "use_for_touch_analysis", "priority"], name="integration_is_acti_bf7e38_idx"),
        ),
        migrations.AddIndex(
            model_name="llmprovideraccount",
            index=models.Index(fields=["provider"], name="integration_provide_8aaf90_idx"),
        ),
    ]
