# Generated by Django 5.2.8 on 2026-04-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_llmprovideraccount'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='llmprovideraccount',
            new_name='integration_is_acti_669090_idx',
            old_name='integration_is_acti_bf7e38_idx',
        ),
        migrations.RenameIndex(
            model_name='llmprovideraccount',
            new_name='integration_provide_8df4a8_idx',
            old_name='integration_provide_8aaf90_idx',
        ),
        migrations.AlterField(
            model_name='llmprovideraccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='llmprovideraccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
