# Generated by Django 5.2.8 on 2025-12-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_merit_staff_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команда'},
        ),
    ]
