# Generated by Django 5.2.8 on 2026-03-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_team_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='visible_phone',
            field=models.CharField(default='', max_length=12, verbose_name='Видимое поле телефона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
    ]
