# Generated by Django 5.2.8 on 2026-03-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_contact_visible_phone_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='visible_phone',
            field=models.CharField(max_length=20, verbose_name='Видимое поле телефона'),
        ),
    ]
