# Generated by Django 5.2.8 on 2026-03-22 06:16

import crm_communications.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0060_automationoutboundmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], max_length=32, verbose_name='Канал')),
                ('subject', models.CharField(blank=True, default='', max_length=255, verbose_name='Тема диалога')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('archived', 'В архиве'), ('closed', 'Закрыт')], default='active', max_length=32, verbose_name='Статус диалога')),
                ('requires_manual_binding', models.BooleanField(default=False, verbose_name='Требует ручной привязки')),
                ('last_message_direction', models.CharField(blank=True, choices=[('incoming', 'Входящее'), ('outgoing', 'Исходящее')], default='', max_length=16, verbose_name='Направление последнего сообщения')),
                ('last_message_preview', models.CharField(blank=True, default='', max_length=500, verbose_name='Превью последнего сообщения')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего сообщения')),
                ('last_incoming_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего входящего')),
                ('last_outgoing_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего исходящего')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='crm.client', verbose_name='Компания')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='crm.contact', verbose_name='Контакт')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='crm.deal', verbose_name='Сделка')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
                'ordering': ('-last_message_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], max_length=32, verbose_name='Канал')),
                ('direction', models.CharField(choices=[('incoming', 'Входящее'), ('outgoing', 'Исходящее')], max_length=16, verbose_name='Направление')),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('email', 'Письмо'), ('service', 'Служебное')], default='text', max_length=32, verbose_name='Тип сообщения')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('queued', 'В очереди'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('received', 'Получено'), ('failed', 'Ошибка'), ('requires_manual_retry', 'Требует ручного повтора')], default='draft', max_length=32, verbose_name='Статус сообщения')),
                ('external_sender_key', models.CharField(blank=True, default='', max_length=255, verbose_name='Внешний отправитель')),
                ('external_recipient_key', models.CharField(blank=True, default='', max_length=255, verbose_name='Внешний получатель')),
                ('subject', models.CharField(blank=True, default='', max_length=255, verbose_name='Тема')),
                ('body_text', models.TextField(blank=True, default='', verbose_name='Текст')),
                ('body_html', models.TextField(blank=True, default='', verbose_name='HTML')),
                ('body_preview', models.CharField(blank=True, default='', max_length=500, verbose_name='Превью')),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255, verbose_name='ID сообщения у провайдера')),
                ('provider_chat_id', models.CharField(blank=True, default='', max_length=255, verbose_name='ID чата у провайдера')),
                ('provider_thread_key', models.CharField(blank=True, default='', max_length=255, verbose_name='Ключ thread у провайдера')),
                ('external_message_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Внешний ID сообщения')),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=255, verbose_name='In-Reply-To')),
                ('references', models.TextField(blank=True, default='', verbose_name='References')),
                ('queued_at', models.DateTimeField(blank=True, null=True, verbose_name='Поставлено в очередь')),
                ('sending_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало отправки')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Получено')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Доставлено')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ошибка')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество повторов')),
                ('last_error_code', models.CharField(blank=True, default='', max_length=128, verbose_name='Последний код ошибки')),
                ('last_error_message', models.TextField(blank=True, default='', verbose_name='Последняя ошибка')),
                ('requires_manual_retry', models.BooleanField(default=False, verbose_name='Требует ручного повтора')),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор в CRM')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_messages', to='crm.client', verbose_name='Компания')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_messages', to='crm.contact', verbose_name='Контакт')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm_communications.conversation', verbose_name='Диалог')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_messages', to='crm.deal', verbose_name='Сделка')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_last_for', to='crm_communications.message', verbose_name='Последнее сообщение'),
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('file', models.FileField(max_length=500, upload_to=crm_communications.models.message_attachment_upload_to, verbose_name='Файл')),
                ('original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Оригинальное имя')),
                ('mime_type', models.CharField(blank=True, default='', max_length=255, verbose_name='MIME type')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='Размер в байтах')),
                ('content_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Content-ID')),
                ('is_inline', models.BooleanField(default=False, verbose_name='Inline')),
                ('provider_attachment_id', models.CharField(blank=True, default='', max_length=255, verbose_name='ID вложения у провайдера')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm_communications.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вложение сообщения',
                'verbose_name_plural': 'Вложения сообщений',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='MessageAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('attempt_number', models.PositiveSmallIntegerField(verbose_name='Номер попытки')),
                ('transport', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], max_length=32, verbose_name='Транспорт')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало попытки')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание попытки')),
                ('status', models.CharField(choices=[('started', 'Запущена'), ('succeeded', 'Успешно'), ('failed', 'Ошибка'), ('retry_scheduled', 'Повтор запланирован')], max_length=32, verbose_name='Статус попытки')),
                ('error_class', models.CharField(blank=True, choices=[('temporary', 'Временная'), ('permanent', 'Постоянная'), ('validation', 'Ошибка валидации'), ('manual_required', 'Нужно ручное действие')], default='', max_length=32, verbose_name='Класс ошибки')),
                ('error_code', models.CharField(blank=True, default='', max_length=128, verbose_name='Код ошибки')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Текст ошибки')),
                ('provider_response_payload', models.JSONField(blank=True, default=dict, verbose_name='Ответ провайдера')),
                ('scheduled_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='Повтор запланирован на')),
                ('is_final', models.BooleanField(default=False, verbose_name='Финальная попытка')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_logs', to='crm_communications.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Лог попытки отправки',
                'verbose_name_plural': 'Логи попыток отправки',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DeliveryFailureQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('failure_type', models.CharField(max_length=64, verbose_name='Тип сбоя')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда попало в очередь')),
                ('resolution_status', models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'В работе'), ('resolved', 'Решена'), ('closed', 'Закрыта')], default='open', max_length=32, verbose_name='Статус обработки')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда решено')),
                ('resolution_comment', models.TextField(blank=True, default='', verbose_name='Комментарий по решению')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_failure_queue_items', to=settings.AUTH_USER_MODEL, verbose_name='Назначено на')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_failure_queue_item', to='crm_communications.message', verbose_name='Сообщение')),
                ('last_attempt_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_queue_items', to='crm_communications.messageattemptlog', verbose_name='Последняя попытка')),
            ],
            options={
                'verbose_name': 'Очередь ошибок доставки',
                'verbose_name_plural': 'Очередь ошибок доставки',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='MessageWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], max_length=32, verbose_name='Канал')),
                ('event_type', models.CharField(max_length=64, verbose_name='Тип события')),
                ('external_event_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Внешний ID события')),
                ('external_message_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Внешний ID сообщения')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда обработано')),
                ('processing_status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processed', 'Обработано'), ('failed', 'Ошибка'), ('ignored', 'Игнорировано')], default='pending', max_length=32, verbose_name='Статус обработки')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Ошибка обработки')),
            ],
            options={
                'verbose_name': 'Webhook событие сообщения',
                'verbose_name_plural': 'Webhook события сообщений',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['external_message_id'], name='crm_communi_externa_0b430e_idx'), models.Index(fields=['processing_status'], name='crm_communi_process_38b48e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_event_id', ''), _negated=True), fields=('channel', 'external_event_id'), name='crm_comm_webhook_unique_channel_external_event_id')],
            },
        ),
        migrations.CreateModel(
            name='ParticipantBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], max_length=32, verbose_name='Канал')),
                ('external_participant_key', models.CharField(max_length=255, verbose_name='Внешний ключ участника')),
                ('external_display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Внешнее имя')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной binding')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее появление')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_bindings', to='crm.client', verbose_name='Компания')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_bindings', to='crm.contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Привязка участника',
                'verbose_name_plural': 'Привязки участников',
                'ordering': ('channel', 'external_participant_key'),
            },
        ),
        migrations.CreateModel(
            name='ConversationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], max_length=32, verbose_name='Канал')),
                ('route_type', models.CharField(max_length=64, verbose_name='Тип маршрута')),
                ('route_key', models.CharField(max_length=255, verbose_name='Ключ маршрута')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной маршрут')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда привязали')),
                ('resolution_source', models.CharField(blank=True, default='', max_length=64, verbose_name='Источник привязки')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_routes', to='crm.client', verbose_name='Компания')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_routes', to='crm.contact', verbose_name='Контакт')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='crm_communications.conversation', verbose_name='Диалог')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_routes', to='crm.deal', verbose_name='Сделка')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conversation_routes', to=settings.AUTH_USER_MODEL, verbose_name='Кто привязал')),
            ],
            options={
                'verbose_name': 'Маршрут диалога',
                'verbose_name_plural': 'Маршруты диалогов',
                'ordering': ('-is_primary', '-id'),
                'indexes': [models.Index(fields=['deal'], name='crm_communi_deal_id_1343c8_idx'), models.Index(fields=['client'], name='crm_communi_client__2ca16b_idx'), models.Index(fields=['is_primary'], name='crm_communi_is_prim_e899dd_idx')],
                'constraints': [models.UniqueConstraint(fields=('channel', 'route_type', 'route_key'), name='crm_comm_route_unique_channel_type_key')],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation'], name='crm_communi_convers_22ea4f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['channel'], name='crm_communi_channel_e45d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['direction'], name='crm_communi_directi_595eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status'], name='crm_communi_status_fe3f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client'], name='crm_communi_client__3ac50f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['deal'], name='crm_communi_deal_id_fa6987_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['provider_message_id'], name='crm_communi_provide_ab8375_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('external_message_id', ''), _negated=True), fields=('channel', 'external_message_id'), name='crm_comm_message_unique_channel_external_message_id'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['channel'], name='crm_communi_channel_5827ec_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['client'], name='crm_communi_client__91f3b0_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['deal'], name='crm_communi_deal_id_8f18fd_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='crm_communi_last_me_7e739b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['requires_manual_binding'], name='crm_communi_require_88a3be_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattemptlog',
            index=models.Index(fields=['message'], name='crm_communi_message_11b528_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattemptlog',
            index=models.Index(fields=['attempt_number'], name='crm_communi_attempt_af821b_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattemptlog',
            index=models.Index(fields=['status'], name='crm_communi_status_c57d77_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattemptlog',
            index=models.Index(fields=['scheduled_retry_at'], name='crm_communi_schedul_40956d_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryfailurequeue',
            index=models.Index(fields=['resolution_status'], name='crm_communi_resolut_1e5193_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryfailurequeue',
            index=models.Index(fields=['assigned_to'], name='crm_communi_assigne_190674_idx'),
        ),
        migrations.AddIndex(
            model_name='participantbinding',
            index=models.Index(fields=['client'], name='crm_communi_client__d75664_idx'),
        ),
        migrations.AddIndex(
            model_name='participantbinding',
            index=models.Index(fields=['contact'], name='crm_communi_contact_042ec1_idx'),
        ),
        migrations.AddConstraint(
            model_name='participantbinding',
            constraint=models.UniqueConstraint(fields=('channel', 'external_participant_key'), name='crm_comm_participant_unique_channel_key'),
        ),
    ]
