# Generated by Django 5.2.8 on 2026-03-22 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0060_automationoutboundmessage'),
        ('crm_communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Следующая попытка не раньше'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['next_attempt_at'], name='crm_communi_next_at_888c20_idx'),
        ),
    ]
