# Generated by Django 5.2.8 on 2026-03-22 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0060_automationoutboundmessage'),
        ('crm_communications', '0002_message_next_attempt_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='touch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_message', to='crm.touch', verbose_name='Связанное касание'),
        ),
    ]
