# Generated by Django 5.2.8 on 2026-03-30 18:26

import crm_communications.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0080_client_company_type'),
        ('crm_communications', '0003_message_touch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealDocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], default='email', max_length=32, verbose_name='Канал')),
                ('recipient', models.CharField(blank=True, default='', max_length=255, verbose_name='Получатель')),
                ('token', models.CharField(db_index=True, default=crm_communications.models.generate_share_token, max_length=32, unique=True, verbose_name='Публичный токен')),
                ('first_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Первое открытие страницы')),
                ('last_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее открытие страницы')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее скачивание PDF')),
                ('open_count', models.PositiveIntegerField(default=0, verbose_name='Количество открытий страницы')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Количество скачиваний PDF')),
                ('first_open_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP первого открытия')),
                ('last_open_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP последнего открытия')),
                ('first_open_user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent первого открытия')),
                ('last_open_user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent последнего открытия')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='crm.dealdocument', verbose_name='Документ сделки')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_document_shares', to='crm_communications.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Публичная отправка документа сделки',
                'verbose_name_plural': 'Публичные отправки документов сделки',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DealDocumentShareEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('event_type', models.CharField(choices=[('email_sent', 'Письмо отправлено'), ('email_failed', 'Ошибка отправки письма'), ('page_opened', 'Страница документа открыта'), ('pdf_downloaded', 'PDF документа скачан')], max_length=32, verbose_name='Тип события')),
                ('happened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Когда произошло')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_document_share_events', to='crm_communications.message', verbose_name='Сообщение')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crm_communications.dealdocumentshare', verbose_name='Публичная отправка')),
            ],
            options={
                'verbose_name': 'Событие публичной отправки документа',
                'verbose_name_plural': 'События публичных отправок документов',
                'ordering': ('-happened_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='dealdocumentshare',
            index=models.Index(fields=['document'], name='crm_communi_documen_0b230f_idx'),
        ),
        migrations.AddIndex(
            model_name='dealdocumentshare',
            index=models.Index(fields=['message'], name='crm_communi_message_f1d363_idx'),
        ),
        migrations.AddIndex(
            model_name='dealdocumentshare',
            index=models.Index(fields=['channel'], name='crm_communi_channel_cb8d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='dealdocumentshare',
            index=models.Index(fields=['last_opened_at'], name='crm_communi_last_op_c3a1df_idx'),
        ),
        migrations.AddIndex(
            model_name='dealdocumentshareevent',
            index=models.Index(fields=['share'], name='crm_communi_share_i_b3fd79_idx'),
        ),
        migrations.AddIndex(
            model_name='dealdocumentshareevent',
            index=models.Index(fields=['event_type'], name='crm_communi_event_t_b49129_idx'),
        ),
        migrations.AddIndex(
            model_name='dealdocumentshareevent',
            index=models.Index(fields=['message'], name='crm_communi_message_96f10e_idx'),
        ),
    ]
