# Generated by Django 5.2.8 on 2026-03-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_communications", "0004_dealdocumentshare_dealdocumentshareevent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealdocumentshareevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("email_sent", "Письмо отправлено"),
                    ("email_failed", "Ошибка отправки письма"),
                    ("document_opened", "Документ открыт"),
                    ("page_opened", "Страница документа открыта"),
                    ("page_viewed", "Страница PDF просмотрена"),
                    ("last_page_reached", "Последняя страница достигнута"),
                    ("pdf_downloaded", "PDF документа скачан"),
                    ("viewer_closed", "Viewer закрыт"),
                    ("time_in_viewer", "Время в viewer"),
                ],
                max_length=32,
                verbose_name="Тип события",
            ),
        ),
    ]
