# Generated by Django 5.2.8 on 2026-03-31 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0084_settlementcontract_advance_percent_and_more"),
        ("crm_communications", "0005_alter_dealdocumentshareevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealdocumentshare",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="crm.dealdocument",
                verbose_name="Документ сделки",
            ),
        ),
        migrations.AddField(
            model_name="dealdocumentshare",
            name="client_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="crm.clientdocument",
                verbose_name="Документ компании",
            ),
        ),
        migrations.AddField(
            model_name="dealdocumentshare",
            name="settlement_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="crm.settlementcontract",
                verbose_name="Договор взаиморасчетов",
            ),
        ),
        migrations.AddIndex(
            model_name="dealdocumentshare",
            index=models.Index(fields=["client_document"], name="crm_communi_client__16b169_idx"),
        ),
        migrations.AddIndex(
            model_name="dealdocumentshare",
            index=models.Index(fields=["settlement_contract"], name="crm_communi_settlem_2add6f_idx"),
        ),
    ]
